# Generated by Django 3.2.7 on 2021-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211021_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Тех.обслуживание'), ('o', 'выдан'), ('a', 'доступен'), ('r', 'забронированный')], default='m', help_text='Статус книги', max_length=1),
        ),
    ]
