# Generated by Django 3.2.7 on 2021-10-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_change', 'Delete/change/add author'),)},
        ),
    ]
